apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- with .Values.tags }}
    first: {{ .machine }}
    second: {{ .rack }}
    third: {{ .drive }}
    {{- end }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
{{ include "mychart.version" . | indent 4 }}
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  ProjectCode: {{ upper .Values.projectCode }}
  pipeline: {{ .Values.projectCode | upper | quote }}
  now: {{ now | date "2006-01-02" | quote }}
  {{- if eq .Values.infra.region "us" }}
  ha: true
  {{- end }}
  {{- $relname := .Release.Name -}}
  {{- with .Values.tags }} 
  Machine Type: {{ .machine | default "NA" | quote }}
  Rack ID: {{ .rack | quote }}
  Storage Type: {{ .drive | upper | quote }}
  Video Card: {{ .vcard | quote }}
  Release: {{ $relname }}
  {{- end }} 
  Lang Used: |-
    {{- range .Values.LangUsed }}
    - {{ . | title | quote }}
    {{- end}}
  Lang Used Index: |-
    {{- range $index, $topping := .Values.LangUsed }}
    - {{ $index }} : {{ $topping }}
    {{- end}}
  {{- template "mychart.systemlables" $ }}


# helm install --debug --dry-run firstdryrun ./mychartvalue
# helm install --debug --dry-run --debug --set costCode=CC0000 firstdryrun ./mychartvalue
# http://masterminds.github.io/sprig/ ====> quote function and upper function 
# https://stackoverflow.com/questions/56395758/what-is-the-difference-between-and-when-creating-a-configmap-from-a-file-i ======> |- and |+
# {{- template "mychart.systemlables" $ }} $ is the current context
